### ISSUE TITLE
Heap dump does not work anymore

### ISSUE THREAD

**Issue by mwdb** [SAP/cf-cli-java-plugin#17]
Hi,

For me the heap dump command does not work any longer.
Reason seems to be that https://github.com/SAP/cf-cli-java-plugin/blob/4b056ddb2ab5931346d693a3e224171b13976a1a/cf_cli_java_plugin.go#L187 looks for an executable jmap. This executable is not available in the application container with the cf community Buildpack.

```
ssh container
find . -name jmap
-> returns empty
 find . -name java
./app/.java-buildpack/open_jdk_jre/bin/java
./app/.java-buildpack/dynatrace_one_agent/agent/conf/runtime/default/java
./app/.java-buildpack/dynatrace_one_agent/agent/bin/1.173.358.20190826-182424/any/java
./app/.java-buildpack/dynatrace_one_agent/log/java
```

See also https://stackoverflow.com/questions/25715067/jmap-command-not-found

Regards,

Martijn

**Comment by TimGerlach** [comment]
Hi @mwdb, thanks a lot for pointing out this issue and please excuse that we haven't replied to you earlier.
As you already pointed out correctly, the issue is related to the fact that the Java buildpack is not shipped with the usual JDK tools like `jmap`, and `jcmd` any longer. This change also came as a surprise to us, but it was decided by the Cloud Foundry Foundation to remove JDK tools due to legal reasons. That said, the plugin can't work as expected. In fact, it just prints out an empty string which I consider a bug we should fix soon.

In case you'd like to get back the required JDK tools and continue using the `cf java` plugin, you have to explicitly request a full JDK in your application manifest via the `JBP_CONFIG_OPEN_JDK_JRE` environment variable like so:

```yaml
---
applications:
- name: spring-music
  memory: 1G
  random-route: true
  path: build/libs/spring-music-1.0.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
  env:
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { repository_root: "https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64", version: 11.+ } }'
```

Note that this requires to use an online buildpack (configured in the `buildpack` property) as staging obviously fails with cache issues when system buildpacks are used which don't have the JDK cached.

Also note that this shall not be considered a recommendation to use a full JDK per se. It's just an option to get tools like `jcmd` and `jmap` back for troubleshooting when you need them, e.g., when using this plugin.

I will update the documentation of the plugin and have a look at the issue with empty responses from the CLI if `jmap` wasn't found in the container.
